---
- name: Check if Grafana GPG key exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/grafana-keyring.gpg
  register: grafana_gpg_key

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /tmp/grafana-keyring.asc
    mode: "0644"
  when: not grafana_gpg_key.stat.exists

- name: Convert Grafana GPG key to binary format
  become: true
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/grafana-keyring.gpg /tmp/grafana-keyring.asc
  when: not grafana_gpg_key.stat.exists
  changed_when: true

- name: Remove the temporary ASCII GPG key
  ansible.builtin.file:
    path: /tmp/grafana-keyring.asc
    state: absent
  when: not grafana_gpg_key.stat.exists

- name: Add Grafana Alloy repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana-keyring.gpg] https://apt.grafana.com stable main"
    state: present

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install Grafana Alloy
  become: true
  ansible.builtin.apt:
    name: alloy
    state: latest
  notify: Restart Alloy service

- name: Clone monitoring repository locally to /tmp
  delegate_to: localhost
  run_once: true
  ansible.builtin.git:
    repo: "git@github.com:{{ github.user }}/monitoring.git"
    dest: "/tmp/monitoring"
    version: main
    depth: 1
    accept_hostkey: true
    update: true

- name: Transfer Alloy config from local machine
  become: true
  ansible.builtin.copy:
    src: "/tmp/monitoring/alloy/{{ alloy_config_name }}"
    dest: "/etc/alloy/config.alloy"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Alloy service

- name: Write env file
  become: true
  ansible.builtin.copy:
    src: "alloy.env"
    dest: "/etc/default/alloy"
    mode: "0644"
  notify: Restart Alloy service
