---
- name: Setup Raspberry Pi Manager
  hosts: raspberrypi_manager
  roles:
    - role: add_cmdline_txt
      tags: add_cmdline_txt

    - role: install_tools
      tags: install_tools
    - role: configure_ssh
      tags: configure_ssh
    - role: configure_motd
      tags: configure_motd
    - role: configure_editor
      tags: configure_editor
    - role: configure_zsh
      tags: configure_zsh

    - role: mount_backup_server
      tags: mount_backup_server
    - role: configure_cron
      tags: configure_cron
    - role: setup_manager_data
      tags: setup_manager_data
    - role: setup_manager_config
      tags: setup_manager_config
    - role: setup_manager_app
      tags: setup_manager_app

    - role: cleanup
      tags: cleanup
