---
- name: Setup Raspberry Pi OctoPi
  hosts: raspberrypi_octopi
  roles:
    - role: configure_network_manager
      tags: configure_network_manager
    - role: configure_editor
      tags: configure_editor
    - role: configure_bash
      tags: configure_bash

    - role: configure_octoprint
      tags: configure_octoprint
    - role: install_node_exporter
      tags: install_node_exporter
    - role: mount_backup_server
      tags: mount_backup_server
    - role: configure_cron
      tags: configure_cron

    - role: cleanup
      tags: cleanup
