---
- name: Setup Raspberry Pi Door
  hosts: raspberrypi_door
  roles:
    - role: install_tools
      tags: install_tools
    - role: configure_ssh
      tags: configure_ssh
    - role: configure_motd
      tags: configure_motd
    - role: configure_editor
      tags: configure_editor
    - role: configure_bash
      tags: configure_bash

    - role: install_nodejs
      tags: install_nodejs
    - role: install_jema2mqtt
      tags: install_jema2mqtt
    - role: install_node_exporter
      tags: install_node_exporter

    - role: cleanup
      tags: cleanup
