---
- name: Setup Raspberry Pi Manager
  hosts: raspberrypi_manager
  roles:
    - role: configure_cmdline_txt
      tags: configure_cmdline_txt

    - role: install_tools
      tags: install_tools
    - role: configure_ssh
      tags: configure_ssh
    - role: configure_motd
      tags: configure_motd
    - role: configure_editor
      tags: configure_editor
    - role: configure_zsh
      tags: configure_zsh

    - role: mount_backup_server
      tags: mount_backup_server
    - role: configure_cron
      tags: configure_cron

    - role: manager_setup_data
      tags: manager_setup_data
    - role: manager_setup_config
      tags: manager_setup_config
    - role: manager_setup_app
      tags: manager_setup_app

    - role: cleanup
      tags: cleanup
