---
- name: Configure cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    user: "{{ ansible_user }}"
    job: "({{ item.job }}) >/dev/null 2>&1"
    minute: "{{ item.minute | default('0') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ cron_jobs }}"
