---
setup_manager_app_clone_repositories:
  - dockyard
  - monitoring
  - nana4-net
  - shellpot
  - home-wiki
  - hass-config

setup_manager_app_base_directories:
  - "repository"
  - "data"
  - "dev"

setup_manager_app_data_directories:
  - grafana
  - loki
  - prometheus
  - alloy
  - ring-face-recognition
  - ring-face-recognition/snapshot
  - wisun2mqtt

setup_manager_app_add_cmdline_txt:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
