---
setup_manager_app_clone_repositories:
  - dockyard
  - monitoring
  - nana4-net
  - shellpot

setup_manager_app_base_directories:
  - "repository"
  - "data"
  - "dev"

setup_manager_app_data_directories:
  - grafana
  - loki
  - prometheus
  - promtail
  - ring-face-recognition
  - ring-face-recognition/snapshot
  - wisun2mqtt

setup_manager_app_add_cmdline_txt:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"

setup_manager_app_cron_jobs:
  - name: "backup"
    job: "{{ ansible_env.HOME }}/repository/shellpot/backup.sh > /dev/null 2>&1"
    hour: 4
  - name: "full-backup"
    job: "{{ ansible_env.HOME }}/repository/shellpot/backup-full.sh > /dev/null 2>&1"
    hour: 5
    day: "1"
  - name: "docker-prune"
    job: "docker container prune -f >/dev/null 2>&1 && docker volume prune -f >/dev/null 2>&1"
    hour: 5
    weekday: "6"
  - name: "smart-report"
    job: "{{ ansible_env.HOME }}/repository/shellpot/smart-report.sh >/dev/null 2>&1"
    hour: 19
    weekday: "5"
