---
- name: Turn off current swap
  ansible.builtin.command: dphys-swapfile swapoff
  become: true
  changed_when: true
  listen: Resize Swapfile

- name: Recreate swapfile with new size
  ansible.builtin.command: dphys-swapfile setup
  become: true
  changed_when: true
  listen: Resize Swapfile

- name: Turn on swap
  ansible.builtin.command: dphys-swapfile swapon
  become: true
  changed_when: true
  listen: Resize Swapfile

- name: Ensure swap enabled at boot
  ansible.builtin.systemd:
    name: dphys-swapfile
    enabled: true
    state: started
  become: true
  listen: Resize Swapfile
